// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lib/proto/cache.proto

/*
Package huton_proto is a generated protocol buffer package.

It is generated from these files:
	lib/proto/cache.proto
	lib/proto/cmd.proto

It has these top-level messages:
	CacheBatch
	Command
	Response
*/
package huton_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CacheBatch struct {
	CacheName        *string  `protobuf:"bytes,1,req,name=cache_name,json=cacheName" json:"cache_name,omitempty"`
	Buf              []byte   `protobuf:"bytes,2,req,name=buf" json:"buf,omitempty"`
	Meta             []uint64 `protobuf:"varint,3,rep,name=meta" json:"meta,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CacheBatch) Reset()                    { *m = CacheBatch{} }
func (m *CacheBatch) String() string            { return proto.CompactTextString(m) }
func (*CacheBatch) ProtoMessage()               {}
func (*CacheBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CacheBatch) GetCacheName() string {
	if m != nil && m.CacheName != nil {
		return *m.CacheName
	}
	return ""
}

func (m *CacheBatch) GetBuf() []byte {
	if m != nil {
		return m.Buf
	}
	return nil
}

func (m *CacheBatch) GetMeta() []uint64 {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*CacheBatch)(nil), "huton_proto.CacheBatch")
}

func init() { proto.RegisterFile("lib/proto/cache.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0xc9, 0x4c, 0xd2,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x4e, 0x4c, 0xce, 0x48, 0xd5, 0x03, 0xb3, 0x85, 0xb8,
	0x33, 0x4a, 0x4b, 0xf2, 0xf3, 0xe2, 0xc1, 0x1c, 0xa5, 0x40, 0x2e, 0x2e, 0x67, 0x90, 0x9c, 0x53,
	0x62, 0x49, 0x72, 0x86, 0x90, 0x2c, 0x17, 0x17, 0x58, 0x65, 0x7c, 0x5e, 0x62, 0x6e, 0xaa, 0x04,
	0xa3, 0x02, 0x93, 0x06, 0x67, 0x10, 0x27, 0x58, 0xc4, 0x2f, 0x31, 0x37, 0x55, 0x48, 0x80, 0x8b,
	0x39, 0xa9, 0x34, 0x4d, 0x82, 0x49, 0x81, 0x49, 0x83, 0x27, 0x08, 0xc4, 0x14, 0x12, 0xe2, 0x62,
	0xc9, 0x4d, 0x2d, 0x49, 0x94, 0x60, 0x56, 0x60, 0xd6, 0x60, 0x09, 0x02, 0xb3, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x5b, 0xa3, 0x25, 0x33, 0x77, 0x00, 0x00, 0x00,
}
