// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

package huton_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CacheSet struct {
	CacheName            string   `protobuf:"bytes,1,opt,name=cache_name,json=cacheName" json:"cache_name,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheSet) Reset()         { *m = CacheSet{} }
func (m *CacheSet) String() string { return proto.CompactTextString(m) }
func (*CacheSet) ProtoMessage()    {}
func (*CacheSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_cache_07b1d7b9a05bf46a, []int{0}
}
func (m *CacheSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheSet.Unmarshal(m, b)
}
func (m *CacheSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheSet.Marshal(b, m, deterministic)
}
func (dst *CacheSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheSet.Merge(dst, src)
}
func (m *CacheSet) XXX_Size() int {
	return xxx_messageInfo_CacheSet.Size(m)
}
func (m *CacheSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheSet.DiscardUnknown(m)
}

var xxx_messageInfo_CacheSet proto.InternalMessageInfo

func (m *CacheSet) GetCacheName() string {
	if m != nil {
		return m.CacheName
	}
	return ""
}

func (m *CacheSet) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *CacheSet) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type CacheDel struct {
	CacheName            string   `protobuf:"bytes,1,opt,name=cache_name,json=cacheName" json:"cache_name,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheDel) Reset()         { *m = CacheDel{} }
func (m *CacheDel) String() string { return proto.CompactTextString(m) }
func (*CacheDel) ProtoMessage()    {}
func (*CacheDel) Descriptor() ([]byte, []int) {
	return fileDescriptor_cache_07b1d7b9a05bf46a, []int{1}
}
func (m *CacheDel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheDel.Unmarshal(m, b)
}
func (m *CacheDel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheDel.Marshal(b, m, deterministic)
}
func (dst *CacheDel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheDel.Merge(dst, src)
}
func (m *CacheDel) XXX_Size() int {
	return xxx_messageInfo_CacheDel.Size(m)
}
func (m *CacheDel) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheDel.DiscardUnknown(m)
}

var xxx_messageInfo_CacheDel proto.InternalMessageInfo

func (m *CacheDel) GetCacheName() string {
	if m != nil {
		return m.CacheName
	}
	return ""
}

func (m *CacheDel) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *CacheDel) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type CacheSetResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheSetResp) Reset()         { *m = CacheSetResp{} }
func (m *CacheSetResp) String() string { return proto.CompactTextString(m) }
func (*CacheSetResp) ProtoMessage()    {}
func (*CacheSetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cache_07b1d7b9a05bf46a, []int{2}
}
func (m *CacheSetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheSetResp.Unmarshal(m, b)
}
func (m *CacheSetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheSetResp.Marshal(b, m, deterministic)
}
func (dst *CacheSetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheSetResp.Merge(dst, src)
}
func (m *CacheSetResp) XXX_Size() int {
	return xxx_messageInfo_CacheSetResp.Size(m)
}
func (m *CacheSetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheSetResp.DiscardUnknown(m)
}

var xxx_messageInfo_CacheSetResp proto.InternalMessageInfo

type CacheDelResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheDelResp) Reset()         { *m = CacheDelResp{} }
func (m *CacheDelResp) String() string { return proto.CompactTextString(m) }
func (*CacheDelResp) ProtoMessage()    {}
func (*CacheDelResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cache_07b1d7b9a05bf46a, []int{3}
}
func (m *CacheDelResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheDelResp.Unmarshal(m, b)
}
func (m *CacheDelResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheDelResp.Marshal(b, m, deterministic)
}
func (dst *CacheDelResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheDelResp.Merge(dst, src)
}
func (m *CacheDelResp) XXX_Size() int {
	return xxx_messageInfo_CacheDelResp.Size(m)
}
func (m *CacheDelResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheDelResp.DiscardUnknown(m)
}

var xxx_messageInfo_CacheDelResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CacheSet)(nil), "huton_proto.CacheSet")
	proto.RegisterType((*CacheDel)(nil), "huton_proto.CacheDel")
	proto.RegisterType((*CacheSetResp)(nil), "huton_proto.CacheSetResp")
	proto.RegisterType((*CacheDelResp)(nil), "huton_proto.CacheDelResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cache service

type CacheClient interface {
	Set(ctx context.Context, in *CacheSet, opts ...grpc.CallOption) (*CacheSetResp, error)
	Del(ctx context.Context, in *CacheDel, opts ...grpc.CallOption) (*CacheDelResp, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) Set(ctx context.Context, in *CacheSet, opts ...grpc.CallOption) (*CacheSetResp, error) {
	out := new(CacheSetResp)
	err := grpc.Invoke(ctx, "/huton_proto.Cache/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Del(ctx context.Context, in *CacheDel, opts ...grpc.CallOption) (*CacheDelResp, error) {
	out := new(CacheDelResp)
	err := grpc.Invoke(ctx, "/huton_proto.Cache/Del", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cache service

type CacheServer interface {
	Set(context.Context, *CacheSet) (*CacheSetResp, error)
	Del(context.Context, *CacheDel) (*CacheDelResp, error)
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/huton_proto.Cache/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Set(ctx, req.(*CacheSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheDel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/huton_proto.Cache/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Del(ctx, req.(*CacheDel))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "huton_proto.Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _Cache_Set_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Cache_Del_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache.proto",
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor_cache_07b1d7b9a05bf46a) }

var fileDescriptor_cache_07b1d7b9a05bf46a = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4e, 0x4c, 0xce,
	0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xce, 0x28, 0x2d, 0xc9, 0xcf, 0x8b, 0x07,
	0x73, 0x94, 0x02, 0xb9, 0x38, 0x9c, 0x41, 0x72, 0xc1, 0xa9, 0x25, 0x42, 0xb2, 0x5c, 0x5c, 0x60,
	0x75, 0xf1, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x9c, 0x60, 0x11,
	0xbf, 0xc4, 0xdc, 0x54, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x26, 0x05, 0x46, 0x0d,
	0x9e, 0x20, 0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x19, 0x2c,
	0x06, 0xe1, 0xc0, 0x8d, 0x74, 0x49, 0xcd, 0xa1, 0x96, 0x91, 0x7c, 0x5c, 0x3c, 0x30, 0x57, 0x06,
	0xa5, 0x16, 0x17, 0xc0, 0xf9, 0x2e, 0xa9, 0x39, 0x20, 0xbe, 0x51, 0x25, 0x17, 0x2b, 0x98, 0x2f,
	0x64, 0xce, 0xc5, 0x0c, 0xf2, 0x89, 0xa8, 0x1e, 0x92, 0x1f, 0xf5, 0x60, 0x5a, 0xa5, 0x24, 0xb1,
	0x0a, 0x83, 0x4c, 0x00, 0x69, 0x04, 0xb9, 0x17, 0x8b, 0x46, 0x97, 0xd4, 0x1c, 0x6c, 0x1a, 0xa1,
	0x56, 0x27, 0xb1, 0x81, 0xc5, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x59, 0x2d, 0x18,
	0x63, 0x01, 0x00, 0x00,
}
